### ISSUE TITLE
Equality behaviour on Features

### ISSUE THREAD

**Issue by sebpuetz** [danieldk/conllx-rs#9]
The `PartialEq` impl on `Features` compares the feature `String` rather than the key-value pairs which leads to some odd behaviour.

https://github.com/danieldk/conllx-rs/blob/72ccc8eb3bf4127d8a1c309e48042840940f9607/src/token.rs#L290-L294

I think that the following examples should be seen as equal:

```Rust
let token = TokenBuilder::new("a")
                .features(Features::from_string("a|b:c"))
                .into();
let other = TokenBuilder::new("a")
                .features(Features::from_string("b:c|a"))
                .into();
assert_ne!(token, other);
```

**Comment by danieldk** [comment]
That was originally the intended behavior, because it was fast and I assumed that features would always be lexicographically ordered.

But comparing features in an order-independent way is more intuitive, but also more expensive. It probably makes most sense to compare the maps and just force map evaluation.
